[package]
name = "wgpu_tidy"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = "24"
encase = "0.10"
winit = "0.30"
pollster = "0"
ouroboros = "0"
cgmath = "0"
bytemuck = "1"
slang = { git = "https://github.com/FloatyMonkey/slang-rs.git" }